config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/search'
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }
  root to: "items#index"
  resources :users, only: :show
  resources :items do
    collection do
      get 'search'
      get 'indicate'
      get 'seek'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :purchase_date
    validates :expiration_date
    validates :image
    validates :quantity, numericality: {
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 100
    }
  end

  def self.search(search)
    if search != ''
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all.order('created_at DESC')
    end
  end

  def self.seek(seek)
    if seek != ''
      where('name LIKE(?)', "%#{seek}%")
    else
      current_user.items.order('created_at DESC')
    end
  end

  scope :sort_items, lambda { |sort_order|
    order(sort_order[:sort])
  }

  scope :sort_list, lambda {
    {
      '並び替え' => '',
      '賞味期限の新しい順' => 'expiration_date desc',
      '賞味期限の古い順' => 'expiration_date asc'
    }
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :indicate, :seek]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @items = if sort_params.present?
               Item.sort_items(sort_params)
             else
               Item.includes(:user).order('created_at DESC')
             end

    @sort_list = Item.sort_list
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def indicate
    @items = if sort_params.present?
               Item.where(user_id: current_user.id).sort_items(sort_params)
             else
               Item.where(user_id: current_user.id).includes(:user).order('created_at DESC')
             end

    @sort_list = Item.where(user_id: current_user.id).sort_list
  end

  def seek
    @items = current_user.items.seek(params[:keyword])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :quantity, :purchase_date, :expiration_date, :memo,
                                 :image).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user == @item.user
  end

  def sort_params
    params.permit(:sort)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: item, local: true do |f|%>
<div class="error-block">
<%= render 'shared/error_messages', model: f.object %>
</div>
  <div class="field">
    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name, class: :form__text, id:"item_name" %>
  </div>

  <div class="field">
    <%= f.label :quantity, "数量" %><br />
    <%= f.number_field :quantity, class: :form__text, min: 1, max: 100, id:"item_quantity"%>
  </div>

  <div class="field">
    <%= f.label :purchase_date, "購入日" %><br />
    <%= f.date_field :purchase_date, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :expiration_date, "賞味期限" %><br />
    <%= f.date_field :expiration_date, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :memo, "メモ" %><br />
    <%= f.text_area :memo, class: :form__text, id:"item_memo" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"item_image" %>
  </div>

  <div class="actions">
    <%= f.submit "追加", class: :form__btn  %>
  </div>
<% end %>

app/views/items/_item.html.erb
<input id="arr_json" type="hidden" value="<%= @items.length %>" class='arr_json'/>
<% @items.each_with_index do |item, i| %>
  <div class="content">
  <div class="image-content">
    <%= link_to image_tag(item.image.variant(resize: '200x200'), class: :card__img ), item_path(item) %>
  </div>  
  <div class="sub-content">
    <div id="name<%=i %>"> <%= item.name %></div>
  </div>
  <div class="sub-content">
    <span class="detail__title">賞味期限</span>
    <div id="expiration-date<%=i %>"><%= item.expiration_date %></div>
  </div>
  <div class="daysleft-content">
      <span id="dead-line<%=i %>">残り<span id="days-left<%=i %>"></span>日</span>
  </div>
  <div class="btn-content">
  <div class="nickname-content">
      <a href="/users/<%= item.user.id %>"><%= item.user.nickname %></a>
      
  </div>
  </div>
  </div>
<% end %> 

app/views/items/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="heading">編集</h2>
      <%= render partial: "form", locals: { item: @item } %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<main class="main">
  <div class="inner">
    <div class=search-block>
    <div class=search-select>
    <%= form_with url: items_path, method: :get, local: true do |f| %>
       <i class="fas fa-sort" style="color: #808080;"></i>
      <% if @sorted.present? %>
        <%= f.select :sort, @sort_list, selected: @sorted, onChange: "javascript: this.form.submit();" %>
      <% else %>
        <%= f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();", class: "form-inline" %>
      <% end %>
    <% end %>
    </div>
    <div class="search-box">
    <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, class: "search-input" %><i class="fas fa-search fa-1x fa-fw" style="color: #808080;"></i>
    <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    </div>
    </div>
    <div class="card-wrapper">
      <%= render partial: "item" %>
    </div>
  </div>
</main>

app/views/items/indicate.html.erb
<main class="main">
  <div class="inner">
  <div class=search-block>
    <div class=search-select>
    <%= form_with url: indicate_items_path, method: :get, local: true do |f| %>
       <i class="fas fa-sort" style="color: #808080;"></i>
      <% if @sorted.present? %>
        <%= f.select :sort, @sort_list, selected: @sorted, onChange: "javascript: this.form.submit();" %>
      <% else %>
        <%= f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
      <% end %>
    <% end %>
    </div>
    <div class="search-box">
    <%= form_with(url: seek_items_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, class: "search-input" %><i class="fas fa-search fa-1x fa-fw" style="color: #808080;"></i>
    <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    </div>
    </div>
  <div class="card-wrapper">
    <%= render partial: "item" %>
  </div>
    <p class="tb"><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-lang="ja" data-size="medium" data-hashtags="FRiDGE私の冷蔵庫" data-text="FRiDGE~私の冷蔵庫~" data-show-count="false">Tweet</a>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></a></p> 
  </div>
</main>

app/views/items/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="heading">保存</h2>
        <%= render partial: "form", locals: { item: @item } %>
    </div>
  </div>
</div>

app/views/items/search.html.erb
<main class="main">
  <div class="inner">
  <div class="search-right">
  <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, class: "search-input" %><i class="fas fa-search fa-1x fa-fw" style="color: #808080;"></i>
  <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  </div>
  <div class="card-wrapper">
    <%= render partial: "item" %>
  </div>
  </div>
</main>

app/views/items/seek.html.erb
<main class="main">
  <div class="inner">
  <div class="search-right">
    <%= form_with(url: seek_items_path, local: true, method: :get, class: "search-form") do |form| %>
    <i class="fas fa-search fa-1x fa-fw" style="color: #808080;"></i><%= form.text_field :keyword, class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <div class="card-wrapper">
    <%= render partial: "item" %>
  </div>
  </div>
</main>

app/views/items/show.html.erb
<main class="main">
  <div class="inner">
    <div class="item-wrapper">
      <div class="item-heading">
        詳細
      </div>
      <% if user_signed_in? && current_user.id == @item.user_id %>
        <div class="item-manage">
          <%= link_to "編集", edit_item_path(@item), class: :item__btn %>
          <%= link_to "削除", item_path(@item), method: :delete, class: :item__btn %>
        </div>
      <% end %>
      <div class="item_block">
        <div class="item_card">
            <div class="image-content">
              <%= link_to image_tag(@item.image.variant(resize: '200x200'), class: :card__img ) %>
            </div>

            <div class="daysleft-detail">
                <span id="dead_line">残り<span id="days_left"></span>日</span>
            </div>
            
            <div class="item-detail">
              <p class="detail__message">
                <%= @item.name %>
              </p>
            </div>
            <div class="item-detail">
              <p class="detail__title">数量</p>
              <p class="detail__message">
                <%= @item.quantity %>
              </p>
            </div>
            <div class="item-detail">
              <p class="detail__title">購入日</p>
              <p id="purchase_date">
                <%= @item.purchase_date %>
              </p>
            </div>
            <div class="item-detail">
              <p class="detail__title">賞味期限</p>
              <p id="expiration_date">
                <%= @item.expiration_date %>
              </p>
            </div>

            <% if @item.memo.present? %>
            <div class="item-detail">
              <p class="detail__title">メモ</p>
              <p class="memo__message">
                <%= @item.memo %>
              </p>
            </div>
            <% end %>
            <div class="btn-contents">
              <div class="back-btn">
               <%= link_to "戻る", root_path %>
              </div>
              <div class="nickname-contents">
                <a href="/users/<%= @item.user.id %>"><%= @item.user.nickname %></a>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</main>