config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/search'
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }
  root to: "items#index"
  resources :users, only: :show
  resources :items do
    collection do
      get 'search'
      get 'indicate'
      get 'seek'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :search_product, only: [:index, :search]

  helper_method :sort_column, :sort_direction

  def index
    @products = Product.order("#{sort_column} #{sort_direction}")
    set_product_column
    set_category_column
  end

  def search
    @results = @p.result.includes(:category)
  end

  private

  def search_product
    @p = Product.ransack(params[:q])
  end

  def set_product_column
    @product_name = Product.select('name').distinct
    @product_shelf_life = Product.select('shelf_life').distinct
    @product_frozen_life = Product.select('frozen_life').distinct
  end

  def set_category_column
    @category_name = Category.select('name').distinct
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : 'name'
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def sort_order(column, name)
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to name, { sort: column, direction: direction }, class: "sort_header #{css_class}"
  end
end

app/views/products/index.html.erb
<main class="main">
  <div class="inner">
   <%= search_form_for @p, url: products_search_path do |f| %>
      <ul class="cp_point">
        <li><i class="fas fa-search fa-1x fa-fw" style="color: #808080;"></i><%= f.label :name, 'キーワード：' %>
        <%= f.search_field :name_cont %>
        </li>
        <br>
        <li><%= f.label :name_eq, '品目：' %>
        <%= f.collection_select :name_eq, @product_name, :name, :name, include_blank: '選択する' %>
        </li>
        <br>
        <li>
        <%= f.label :category_name_eq, 'カテゴリー：' %>
        <%= f.collection_select :category_name_eq, @category_name, :name, :name, include_blank: '選択する' %>
        </li>
        <br>
        <li>
        <%= f.label :shelf_life, '保存期間：' %>
        <%= f.radio_button :shelf_life_lteq, '7' %>
        1週間以内
        <%= f.radio_button :shelf_life_lteq, '14' %>
        2週間以内
        <%= f.radio_button :shelf_life_lteq, '21' %>
        3週間以内
        <%= f.radio_button :shelf_life_lteq, '30' %>
        1ヶ月以内
        <%= f.radio_button :shelf_life_lteq, '90' %>
        3ヶ月以内
        </li>
        <br>
        <li>
        <%= f.label :frozen_life_eq, '冷凍：' %>
        <%= f.radio_button :frozen_life_eq, '21' %>
        3週間
        <%= f.radio_button :frozen_life_eq, '30' %>
        1ヶ月
        <%= f.radio_button :frozen_life_eq, '60' %>
        2ヶ月
        <%= f.radio_button :frozen_life_eq, '180' %>
        6ヶ月
        </li>
        <br>
        <%= f.submit '検索', class: :form__btn %>
      </ul> 
      <% end %>
      <table class="cp_table">
        <thead>
        <tr>
        <th scope="column"><%= sort_order "name", "品目" %></th>
        <th scope="column"><%= sort_order "shelf_life", "保存期間" %></th>
        <th scope="column" ><%= sort_order "frozen_life", "冷凍" %></th>
        <th>メモ</th>
        </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.name %></td>
              <td><%= product.shelf_life %>日</td>
              <td><%= product.frozen_life %>日</td>
              <td><%= product.info %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <br>
    <br>
  </div>
</main>

app/views/products/search.html.erb
<main class="main">
  <div class="inner">
    <% if @results.length !=0 %>
        <table class="cp_table">
        <thead>
        <tr>
        <th>品目</th>
        <th>保存期間</th>
        <th>冷凍</th>
        <th>メモ</th>
        </tr>
        </thead>
          <tbody>
          <br>
          <% @results.each do |result| %>
          <tr>
            <td><%= result.name %></td>
            <td><%= result.shelf_life %>日</td>
            <td><%= result.frozen_life %>日</td>
            <td><%= result.info %></td>
          </tr>
          <% end %>
          </tbody>
        </table>
      <% else %>
        <table class="cp_table">
        <thead>
        <tr>
        <th></th>
        </tr>
        </thead>
        <tbody>
        <br>
        <tr>
          <td>該当する商品はありません</td>
        </tr>
        </tbody>
         </table>
      <% end %>
      <br>
      <br>
  </div>
</main>